name: PHPUnit Test Suite
on:
  schedule:
    - cron: 0 9 * * 1
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  skeleton-test:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@1.6.1
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Composer self-update
        run: composer self-update
      - name: Install Skeleton
        run: |
          composer create-project --no-interaction mezzio/mezzio-skeleton app
          cd app
          composer require --no-interaction netglue/laminas-symfony-console "dev-master"
          php vendor/bin/cli
